# **Logistic Regression**

# Step-1: Import Library of python
1. Numpy ( Array transformation)
2. Pandas ( Data Wrangling/Cleaning) (Data Preprocessing)
3. Matplot library ( Visualization)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

# Step-2: Import the dataset
Using Pandas Library

In [2]:
pa=pd.read_csv('/content/drive/MyDrive/DM22_23/Social_Network_Ads(1).csv')

Data information

In [7]:
pa.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
pa.shape # to get number of rows and columns

(400, 5)

In [10]:
pa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [20]:
pa.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [24]:
X1=pa.iloc[:,[1,2,3]] # independent variables
y1=pa.iloc[:,4]

In [ ]:
X1

In [11]:
# Extract required columns( dependent and independent variable)
X=pa.iloc[:,[1,2,3]].values # independent variables
y=pa.iloc[:,4].values  # dependent variables

In [21]:
print(X)

[[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [1 36 33000]
 [0 49 36000]]


Label Encoding to convert Gender(Text) to Numerical Data

In [15]:
from sklearn.preprocessing import LabelEncoder
lcoding_X=LabelEncoder()
X[:,0]=lcoding_X.fit_transform(X[:,0])

In [16]:
X

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

# Step-3: Split Data into Train and Test

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=21)

# Step-4: Feature Scaling

In [ ]:
X_train

In [28]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_train

# Step-5: Implementing Logistic Regression

In [30]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

Predictions

In [31]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

# Create Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print('Confusion Matrix')
print(cm)

Confusion Matrix
[[77  4]
 [14 25]]


In [33]:
from sklearn.metrics import  accuracy_score
from sklearn.metrics import  precision_score
from sklearn.metrics import  recall_score
from sklearn.metrics import  f1_score

In [40]:
print('Accuracy:%.2f'%(accuracy_score(y_test,y_pred)*100))
print('Precision:%.3f'%(precision_score(y_test,y_pred)))
print('Recall:%.3f'%(recall_score(y_test,y_pred)))
print('F-Measure:%.3f'%(f1_score(y_test,y_pred)))

Accuracy:85.00
Precision:0.862
Recall:0.641
F-Measure:0.735


In [41]:
from sklearn.naive_bayes import GaussianNB
classifierNB=GaussianNB()
classifierNB.fit(X_train,y_train)

GaussianNB()

In [42]:
y_predNB=classifierNB.predict(X_test)
y_predNB

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [43]:
cm1=confusion_matrix(y_test,y_predNB)
print('Confusion Matrix-NB')
print(cm1)

Confusion Matrix-NB
[[77  4]
 [12 27]]


In [45]:
print('AccuracyNB:%.2f'%(accuracy_score(y_test,y_predNB)*100))
print('PrecisionNB:%.3f'%(precision_score(y_test,y_predNB)))
print('RecallNB:%.3f'%(recall_score(y_test,y_predNB)))
print('F-MeasureNB:%.3f'%(f1_score(y_test,y_predNB)))
print('**********************************************')
print('Accuracy:%.2f'%(accuracy_score(y_test,y_pred)*100))
print('Precision:%.3f'%(precision_score(y_test,y_pred)))
print('Recall:%.3f'%(recall_score(y_test,y_pred)))
print('F-Measure:%.3f'%(f1_score(y_test,y_pred)))

AccuracyNB:86.67
PrecisionNB:0.871
RecallNB:0.692
F-MeasureNB:0.771
**********************************************
Accuracy:85.00
Precision:0.862
Recall:0.641
F-Measure:0.735
